# .travis.yml file based on:
# https://gist.github.com/dan-blanchard/7045057

language: python
python:
  - "2.7"
  - "3.5"
env:
  - ATOM=0.3
  - ATOM=1.0
matrix:
  exclude:
    - python: "3.5"
      env: ATOM=0.3
    - python: "2.7"
      env: ATOM=1.0

# Setup anaconda
before_install:
  - mkdir -p download
  - cd download
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - cd ..
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
  - travis_retry conda install --yes python=$TRAVIS_PYTHON_VERSION numpy bokeh h5py jupyter scipy networkx future
  - if [[ $ATOM == 0.3 ]]; then conda install --yes atom; fi
  - if [[ $ATOM == 1.0 ]]; then pip install cppy; pip install git+https://github.com/nucleic/atom.git@1.0.0-dev; fi
  - pip install coveralls
  - wget "https://drive.google.com/uc?export=download&id=0BxaPKTZqyVchaXc1V3hlejRaY2M" -O test_data.tar.gz
  - tar xzvf test_data.tar.gz -C tests/

# use conda to install packages
install:
 # Coverage packages are on my binstar channel
  - pip install watchdog

# execute scripts
script:
  - coverage run -m unittest discover
after_script:
  - coveralls

# necessary to run on new container-based infrastructure
sudo: false

cache:
  directories:
    - $HOME/download
    - $HOME/.cache/pip
